Preparar el dataset para poder entrenar el modelo

Link de descarga: https://www.kaggle.com/datasets/deepu1109/star-dataset

In [1]:
import pandas as pd

df = pd.read_csv("data/predict_star_type.csv")
df

,Temperature (K),Luminosity(L/Lo),Radius(R/Ro),Absolute magnitude(Mv),Star type,Star color,Spectral Class
0,3068,0.002400,0.1700,16.12,0,Red,M
1,3042,0.000500,0.1542,16.60,0,Red,M
2,2600,0.000300,0.1020,18.70,0,Red,M
3,2800,0.000200,0.1600,16.65,0,Red,M
4,1939,0.000138,0.1030,20.06,0,Red,M
...,...,...,...,...,...,...,...
235,38940,374830.000000,1356.0000,-9.93,5,Blue,O
236,30839,834042.000000,1194.0000,-10.63,5,Blue,O
237,8829,537493.000000,1423.0000,-10.73,5,White,A
238,9235,404940.000000,1112.0000,-11.23,5,White,A
239,37882,294903.000000,1783.0000,-7.80,5,Blue,O

In [3]:
df[( df["Temperature (K)"].isna() | df["Radius(R/Ro)"].isna() | df["Absolute magnitude(Mv)"].isna())]

Empty DataFrame
Columns: [Temperature (K), Luminosity(L/Lo), Radius(R/Ro), Absolute magnitude(Mv), Star type, Star color, Spectral Class]
Index: []

In [4]:
df["Temperature (K)"].describe()

count      240.000000
mean     10497.462500
std       9552.425037
min       1939.000000
25%       3344.250000
50%       5776.000000
75%      15055.500000
max      40000.000000
Name: Temperature (K), dtype: float64

In [5]:
df["Temperature (K)"].nunique()

228

In [6]:
df['Radius(R/Ro)'].describe()

count     240.000000
mean      237.157781
std       517.155763
min         0.008400
25%         0.102750
50%         0.762500
75%        42.750000
max      1948.500000
Name: Radius(R/Ro), dtype: float64

In [7]:
df['Radius(R/Ro)'].nunique()

216

In [9]:
df['Absolute magnitude(Mv)'].describe()

count    240.000000
mean       4.382396
std       10.532512
min      -11.920000
25%       -6.232500
50%        8.313000
75%       13.697500
max       20.060000
Name: Absolute magnitude(Mv), dtype: float64

In [10]:
df["temperature"] = df["Temperature (K)"].copy()
df["radius"] = df["Radius(R/Ro)"].copy()
df["abs_mag"] = df["Absolute magnitude(Mv)"].copy()


df

,Temperature (K),Luminosity(L/Lo),Radius(R/Ro),Absolute magnitude(Mv),Star type,Star color,Spectral Class,temperature,radius,abs_mag
0,3068,0.002400,0.1700,16.12,0,Red,M,3068,0.1700,16.12
1,3042,0.000500,0.1542,16.60,0,Red,M,3042,0.1542,16.60
2,2600,0.000300,0.1020,18.70,0,Red,M,2600,0.1020,18.70
3,2800,0.000200,0.1600,16.65,0,Red,M,2800,0.1600,16.65
4,1939,0.000138,0.1030,20.06,0,Red,M,1939,0.1030,20.06
...,...,...,...,...,...,...,...,...,...,...
235,38940,374830.000000,1356.0000,-9.93,5,Blue,O,38940,1356.0000,-9.93
236,30839,834042.000000,1194.0000,-10.63,5,Blue,O,30839,1194.0000,-10.63
237,8829,537493.000000,1423.0000,-10.73,5,White,A,8829,1423.0000,-10.73
238,9235,404940.000000,1112.0000,-11.23,5,White,A,9235,1112.0000,-11.23
239,37882,294903.000000,1783.0000,-7.80,5,Blue,O,37882,1783.0000,-7.80

In [12]:
df[["temperature", "radius", "abs_mag"]].to_csv("data/final_dataset.csv", index=False)